import { jsPDF } from "jspdf";
import type { AnalysisResult } from "~lib/analyzer";

export async function generateCertificate(analysis: AnalysisResult, sessionTitle: string) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  // --- Background & Header ---
  // Add a subtle border
  doc.setLineWidth(1);
  doc.setDrawColor(200, 200, 200);
  doc.rect(10, 10, 190, 277);

  // Logo Placeholder
  doc.setFillColor(37, 99, 235); // Blue-600
  doc.circle(30, 30, 10, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.text("C", 28, 32);

  // Title
  doc.setTextColor(30, 41, 59); // Slate-800
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Proof of Process Certificate", 50, 32);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139); // Slate-500
  doc.text(`Generated by CogniTrace | ${new Date().toLocaleDateString()}`, 50, 40);

  // --- Session Info ---
  doc.setDrawColor(226, 232, 240);
  doc.line(20, 50, 190, 50);

  doc.setFontSize(12);
  doc.setTextColor(71, 85, 105);
  doc.text("Document Title:", 20, 65);
  doc.setFont("helvetica", "bold");
  doc.text(sessionTitle || "Untitled Document", 60, 65);

  doc.setFont("helvetica", "normal");
  doc.text("Session ID:", 20, 75);
  doc.setFont("helvetica", "mono");
  doc.setFontSize(10);
  doc.text("UUID-PLACEHOLDER-XXXX-YYYY", 60, 75); // Should come from session data

  // --- Integrity Score (The Big Number) ---
  const score = analysis.integrityScore;
  let color = [34, 197, 94]; // Green
  if (score < 80) color = [234, 179, 8]; // Yellow
  if (score < 50) color = [239, 68, 68]; // Red

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(20, 90, 170, 60, 3, 3, "F");
  
  doc.setFontSize(16);
  doc.setTextColor(71, 85, 105);
  doc.setFont("helvetica", "bold");
  doc.text("Integrity Score", 105, 110, { align: "center" });

  doc.setFontSize(40);
  doc.setTextColor(color[0], color[1], color[2]);
  doc.text(`${score}%`, 105, 130, { align: "center" });

  // --- Detailed Metrics ---
  doc.setFontSize(14);
  doc.setTextColor(30, 41, 59);
  doc.text("Process Metrics", 20, 170);
  doc.line(20, 175, 190, 175);

  const metrics = [
    { label: "Active Editing Time", value: `${Math.round(analysis.activeTime / 1000 / 60)} minutes` },
    { label: "Total Events", value: analysis.totalEvents.toString() },
    { label: "Paste Count", value: analysis.pasteCount.toString() },
    { label: "Original Content", value: `${analysis.sourceBreakdown.original}%` },
    { label: "Entropy Level", value: `${analysis.entropy.toFixed(2)} bits` }
  ];

  let y = 190;
  doc.setFontSize(11);
  metrics.forEach(m => {
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139);
    doc.text(m.label, 30, y);
    
    doc.setFont("helvetica", "bold");
    doc.setTextColor(51, 65, 85);
    doc.text(m.value, 120, y);
    y += 10;
  });

  // --- Footer / Verification ---
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text("This certificate cryptographically verifies that the document creation process was monitored by CogniTrace.", 105, 270, { align: "center" });
  doc.text("Scan QR code to verify online (Mockup)", 105, 275, { align: "center" });

  // Save
  doc.save(`CogniTrace_Certificate_${Date.now()}.pdf`);
}
